export const PROVINCIAS_ESPANOLAS = [
  "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila", "Badajoz", "Baleares", "Barcelona", "Burgos", "Cáceres",
  "Cádiz", "Cantabria", "Castellón", "Ciudad Real", "Córdoba", "Cuenca", "Girona", "Granada", "Guadalajara",
  "Guipúzcoa", "Huelva", "Huesca", "Jaén", "La Rioja", "Las Palmas", "León", "Lleida", "Lugo", "Madrid", "Málaga", 
  "Murcia", "Navarra", "Ourense", "Palencia", "Pontevedra", "Salamanca", "Santa Cruz de Tenerife", "Segovia", 
  "Sevilla", "Soria", "Tarragona", "Teruel", "Toledo", "Valencia", "Valladolid", "Vizcaya", "Zamora", "Zaragoza", 
  "Ceuta", "Melilla"
].sort();

export const CIUDADES_POR_PROVINCIA: Record<string, string[]> = {
  "Álava": ["Vitoria-Gasteiz", "Llodio", "Amurrio"],
  "Albacete": ["Albacete", "Hellín", "Villarrobledo", "Almansa"],
  "Alicante": ["Alicante", "Elche", "Torrevieja", "Orihuela", "Benidorm", "Alcoy", "Elda", "Denia"],
  "Almería": ["Almería", "Roquetas de Mar", "El Ejido", "Níjar", "Adra"],
  "Asturias": ["Gijón", "Oviedo", "Avilés", "Siero", "Langreo"],
  "Ávila": ["Ávila", "Arévalo", "Arenas de San Pedro"],
  "Badajoz": ["Badajoz", "Mérida", "Don Benito", "Almendralejo", "Villanueva de la Serena"],
  "Baleares": ["Palma de Mallorca", "Ibiza", "Mahón", "Ciudadela", "Inca", "Manacor"],
  "Barcelona": ["Barcelona", "L'Hospitalet de Llobregat", "Badalona", "Terrassa", "Sabadell", "Mataró", "Santa Coloma de Gramenet", "Sant Cugat del Vallès", "Cornellà de Llobregat", "Sant Boi de Llobregat", "Manresa", "Rubí", "Vilanova i la Geltrú", "Viladecans", "Castelldefels", "Granollers", "Cerdanyola del Vallès", "Mollet del Vallès", "Esplugues de Llobregat", "Gavà", "Sant Feliu de Llobregat", "Vic", "Igualada", "Vilafranca del Penedès", "Ripollet", "Sant Adrià de Besòs", "Montcada i Reixac", "Sant Joan Despí", "Barberà del Vallès", "Sant Pere de Ribes", "Sitges", "Martorell", "Premià de Mar", "Pineda de Mar", "Sant Vicenç dels Horts", "Sant Andreu de la Barca"],
  "Burgos": ["Burgos", "Miranda de Ebro", "Aranda de Duero"],
  "Cáceres": ["Cáceres", "Plasencia", "Navalmoral de la Mata"],
  "Cádiz": ["Jerez de la Frontera", "Algeciras", "Cádiz", "San Fernando", "El Puerto de Santa María", "Chiclana de la Frontera", "Sanlúcar de Barrameda", "La Línea de la Concepción"],
  "Cantabria": ["Santander", "Torrelavega", "Castro-Urdiales", "Camargo", "Piélagos"],
  "Castellón": ["Castellón de la Plana", "Vila-real", "Burriana", "Vinaròs", "Benicarló"],
  "Ciudad Real": ["Ciudad Real", "Puertollano", "Tomelloso", "Alcázar de San Juan", "Valdepeñas"],
  "Córdoba": ["Córdoba", "Lucena", "Puente Genil", "Montilla", "Priego de Córdoba"],
  "Cuenca": ["Cuenca", "Tarancón", "Quintanar del Rey"],
  "Girona": ["Girona", "Figueres", "Blanes", "Lloret de Mar", "Olot", "Salt", "Palafrugell", "Sant Feliu de Guíxols"],
  "Granada": ["Granada", "Motril", "Almuñécar", "Armilla", "Maracena"],
  "Guadalajara": ["Guadalajara", "Azuqueca de Henares"],
  "Guipúzcoa": ["San Sebastián", "Irun", "Rentería", "Éibar", "Zarautz", "Mondragón"],
  "Huelva": ["Huelva", "Lepe", "Almonte", "Moguer", "Isla Cristina"],
  "Huesca": ["Huesca", "Barbastro", "Monzón"],
  "Jaén": ["Jaén", "Linares", "Andújar", "Úbeda", "Alcalá la Real", "Martos"],
  "La Rioja": ["Logroño", "Calahorra", "Arnedo"],
  "Las Palmas": ["Las Palmas de Gran Canaria", "Telde", "Santa Lucía de Tirajana", "Arrecife", "San Bartolomé de Tirajana", "Arucas", "Puerto del Rosario"],
  "León": ["León", "Ponferrada", "San Andrés del Rabanedo"],
  "Lleida": ["Lleida", "Tàrrega", "Balaguer", "Mollerussa"],
  "Lugo": ["Lugo", "Monforte de Lemos", "Viveiro"],
  "Madrid": ["Madrid", "Móstoles", "Alcalá de Henares", "Fuenlabrada", "Leganés", "Getafe", "Alcorcón", "Torrejón de Ardoz", "Parla", "Alcobendas", "Las Rozas de Madrid", "San Sebastián de los Reyes", "Pozuelo de Alarcón", "Coslada", "Rivas-Vaciamadrid", "Valdemoro", "Majadahonda", "Collado Villalba", "Aranjuez", "Arganda del Rey", "Boadilla del Monte", "Pinto", "Colmenar Viejo", "Tres Cantos", "San Fernando de Henares"],
  "Málaga": ["Málaga", "Marbella", "Mijas", "Fuengirola", "Vélez-Málaga", "Estepona", "Torremolinos", "Benalmádena", "Rincón de la Victoria", "Antequera", "Ronda", "Alhaurín de la Torre"],
  "Murcia": ["Murcia", "Cartagena", "Lorca", "Molina de Segura", "Alcantarilla", "Mazarrón", "Cieza", "Águilas", "Yecla", "Torre-Pacheco", "San Javier", "Totana"],
  "Navarra": ["Pamplona", "Tudela", "Barañáin", "Valle de Egüés", "Zizur Mayor"],
  "Ourense": ["Ourense", "Carballiño", "Verín"],
  "Palencia": ["Palencia", "Aguilar de Campoo"],
  "Pontevedra": ["Vigo", "Pontevedra", "Vilagarcía de Arousa", "Redondela", "Cangas"],
  "Salamanca": ["Salamanca", "Santa Marta de Tormes", "Béjar"],
  "Santa Cruz de Tenerife": ["Santa Cruz de Tenerife", "San Cristóbal de La Laguna", "Arona", "Adeje", "Granadilla de Abona", "La Orotava", "Los Realejos", "Puerto de la Cruz"],
  "Segovia": ["Segovia", "Cuéllar"],
  "Sevilla": ["Sevilla", "Dos Hermanas", "Alcalá de Guadaíra", "Utrera", "Mairena del Aljarafe", "Écija", "La Rinconada", "Los Palacios y Villafranca", "Coria del Río", "Carmona", "Morón de la Frontera", "Lebrija", "Camas"],
  "Soria": ["Soria"],
  "Tarragona": ["Tarragona", "Reus", "Tortosa", "El Vendrell", "Cambrils", "Salou", "Valls", "Calafell", "Amposta"],
  "Teruel": ["Teruel", "Alcañiz"],
  "Toledo": ["Toledo", "Talavera de la Reina", "Illescas", "Seseña", "Torrijos"],
  "Valencia": ["Valencia", "Torrent", "Gandia", "Paterna", "Sagunto", "Alzira", "Mislata", "Burjassot", "Ontinyent", "Aldaia", "Manises", "Alaquàs", "Xàtiva", "Xirivella", "Sueca"],
  "Valladolid": ["Valladolid", "Laguna de Duero", "Medina del Campo", "Arroyo de la Encomienda"],
  "Vizcaya": ["Bilbao", "Barakaldo", "Getxo", "Portugalete", "Santurtzi", "Basauri", "Leioa", "Galdakao", "Sestao"],
  "Zamora": ["Zamora", "Benavente"],
  "Zaragoza": ["Zaragoza", "Calatayud", "Utebo", "Ejea de los Caballeres"]
};
